// Code generated by hero.
// source: F:\Projetos\projetos-golang\src\ocp.com\dino\dynowebportal\dinoTemplate\metrics\metrics.html
// DO NOT EDIT!
package dinoTemplate

import (
	"io"

	"github.com/shiyanhui/hero"
	"ocp.com/dino/databaselayer"
)

func HandleMetrics(animals []databaselayer.Animal, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Jurassic World</title>

    <!-- Bootstrap core CSS -->
    <link href="../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../css/main.css" rel="stylesheet">
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Sistema de Jurassic Park</h3>
              <nav class="nav nav-masthead">
                <a class="nav-link active" href="../index.html">Home</a>
                <a class="nav-link" href="../metrics/metrics.html">Métricas</a>
                <a class="nav-link" href="../info/info.html">info</a>
              </nav>
            </div>
          </div>

          <div class="inner cover">

          `)
	_buffer.WriteString(`
         <div class="panel panel-default">
            <div class="panel-heading">Medidas dos Dinossauros</div>
            <font color="black">
            <table class="table" id="dinometrics">
              <thead>
                <tr>
                <th>Apelido</th>
                <th>Batimento Cardíaco</th>
                <th>Pressão Arterial</th>
                </tr>
              </thead>
            `)
	for _, animal := range animals {
		_buffer.WriteString(`
              <tr>
               <td class="dinoname">`)
		hero.EscapeHTML(animal.Nickname, _buffer)
		_buffer.WriteString(`</td>
                <td class="dinohr"></td>
                <td class="dinobp"></td>
              </tr>
              `)
	}
	_buffer.WriteString(` 
            </table>
            </font>
         </div>
        </div>

        <div class="mastfoot">
          <div class="inner">
            <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script>
    window.jQuery || document.write('<script src="./js/jquery.min.js"><\/script>')
  </script>
  <script src="../js/bootstrap.min.js"></script>
  <script src="../js/metrics.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="../js/ie10-viewport-bug-workaround.js"></script>
`)

	_buffer.WriteString(`

  </body>
</html>
`)
	w.Write(_buffer.Bytes())

}
